//
//  AddPlayerDetailsWorker.swift
//  SampleCS
//
//  Created by Adam Johnston on 13/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FBSDKCoreKit
import FBSDKLoginKit
import Firebase

class AddPlayerDetailsWorker
{
    let db = Firestore.firestore()
    func doSomeWork()
    {
    }
    
    func submitPlayerDetailsToServer(details: AddPlayerDetails.Something.Request, currentInteractor: AddPlayerDetailsInteractor){
        if(details.firstName != ""){
            db.collection("users").whereField("Userid", isEqualTo: details.userId)
                .getDocuments() { (querySnapshot, err) in
                    if let err = err {
                        print("Error getting documents: \(err)")
                    } else {
                        for document in querySnapshot!.documents {
                            print("\(document.documentID) => \(document.data())")
                            self.db.collection("users").document(document.documentID).updateData([
                                "firstName": details.firstName,
                                "lastName": details.lastName,
                                "userRating": details.userRating,
                                "teamOption": details.teamOption,
                                "teamCaptain": details.teamCaptain,
                                "id" : UUID().uuidString
                                ])
                            currentInteractor.playerDetailsAddedToServerSuccess(result: details, currentInteractor: currentInteractor)
                        }
                    }
            }
        }
    }
}
