//
//  AddPlayerDetailsRouter.swift
//  SampleCS
//
//  Created by Adam Johnston on 13/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddPlayerDetailsRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToSomewhere()
    var loginDetails: Array<String>? {get set}
}

protocol AddPlayerDetailsDataPassing
{
    var dataStore: AddPlayerDetailsDataStore? { get }
}

class AddPlayerDetailsRouter: NSObject, AddPlayerDetailsRoutingLogic, AddPlayerDetailsDataPassing
{
    var loginDetails: Array<String>?
    weak var viewController: AddPlayerDetailsViewController?
    var dataStore: AddPlayerDetailsDataStore?
    
    func routeToSomewhere(){
        viewController?.performSegue(withIdentifier: "joinsquad", sender: nil)
    }
    
    // MARK: Routing
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    //func navigateToSomewhere(source: AddPlayerDetailsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    //func passDataToSomewhere(source: AddPlayerDetailsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
