//
//  AddPlayerDetailsInteractor.swift
//  SampleCS
//
//  Created by Adam Johnston on 13/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol AddPlayerDetailsBusinessLogic
{
    func doSomething(request: AddPlayerDetails.Something.Request)
    func submitPlayerDetailsToServer(add : AddPlayerDetails.Something.Request , currentInteractor: AddPlayerDetailsInteractor)
    func playerDetailsAddedToServerSuccess(result : AddPlayerDetails.Something.Request , currentInteractor: AddPlayerDetailsInteractor)
}

protocol AddPlayerDetailsDataStore
{
    //var name: String { get set }
}

class AddPlayerDetailsInteractor: AddPlayerDetailsBusinessLogic, AddPlayerDetailsDataStore
{
    func submitPlayerDetailsToServer(add : AddPlayerDetails.Something.Request, currentInteractor: AddPlayerDetailsInteractor) {
        worker = AddPlayerDetailsWorker()
        self.worker?.submitPlayerDetailsToServer(details: add, currentInteractor: currentInteractor)
    }
    
    func playerDetailsAddedToServerSuccess(result: AddPlayerDetails.Something.Request, currentInteractor: AddPlayerDetailsInteractor) {
        presenter?.displayJoinTeam(showing: result)
    }
    
    var presenter: AddPlayerDetailsPresentationLogic?
    var worker: AddPlayerDetailsWorker?
    //var name: String = ""
    // MARK: Do something
    
    func doSomething(request: AddPlayerDetails.Something.Request)
    {
        worker = AddPlayerDetailsWorker()
        worker?.doSomeWork()
        let response = AddPlayerDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
