//
//  TeamSelectionRouter.swift
//  SampleCS
//
//  Created by Adam Johnston on 15/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TeamSelectionRoutingLogic
{
    var groupID: String {get set}
    func routeToPlayerInfo()
    var playerDetails : JoinSquad.Something.PlayerModel {get set}

}

protocol TeamSelectionDataPassing
{
  var dataStore: TeamSelectionDataStore? { get }
}

class TeamSelectionRouter: NSObject, TeamSelectionRoutingLogic, TeamSelectionDataPassing
{
    
  var playerDetails: JoinSquad.Something.PlayerModel = JoinSquad.Something.PlayerModel()
  var groupID: String = ""
  weak var viewController: TeamSelectionViewController?
  var dataStore: TeamSelectionDataStore?
  
  func routeToPlayerInfo() {
        viewController?.performSegue(withIdentifier: "playerInformation", sender: nil)
  }

  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TeamSelectionViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TeamSelectionDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
