//
//  TeamSelectionInteractor.swift
//  SampleCS
//
//  Created by Adam Johnston on 15/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TeamSelectionBusinessLogic
{
  func doSomething(request: TeamSelection.Something.TeamRequest, currentInteractor: TeamSelectionInteractor)
  func teamResonseSuccess(result: NSDictionary)
}

protocol TeamSelectionDataStore
{
  //var name: String { get set }
}

class TeamSelectionInteractor: TeamSelectionBusinessLogic, TeamSelectionDataStore
{
  var presenter: TeamSelectionPresentationLogic?
  var worker: TeamSelectionWorker?
  //var name: String = ""
  // MARK: Do something
  
  func doSomething(request: TeamSelection.Something.TeamRequest, currentInteractor: TeamSelectionInteractor)
  {
    worker = TeamSelectionWorker()
    worker?.doSomeWork(teamRequest: request, currentInteractor: currentInteractor)
    
    let response = TeamSelection.Something.TeamResponse()
    presenter?.presentSomething(response: response)
  }
    
    func teamResonseSuccess(result: NSDictionary){
        presenter?.displayTeamData(showing: result)
    }
}
