//
//  TeamSelectionPresenter.swift
//  SampleCS
//
//  Created by Adam Johnston on 15/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TeamSelectionPresentationLogic
{
  func displayTeamData(showing: NSMutableArray)
}

class TeamSelectionPresenter: TeamSelectionPresentationLogic
{
  weak var viewController: TeamSelectionDisplayLogic?
  
  // MARK: Do something
  
  func displayTeamData(showing: NSMutableArray){
    
    let playerTeamA = TeamSelection.Something.PlayerModel()
    let playerTeamB = TeamSelection.Something.PlayerModel()
    let playerModel = TeamSelection.Something.TeamResponse(playerA: playerTeamA, playerB: playerTeamB, groupArrayA: [], groupArrayB: [])

    for i in 0...showing.count-1{
        let dict : NSDictionary = showing.object(at: i) as! NSDictionary
        if((dict.object(forKey: "teamOption") as! String) == "Team A"){
            let playerTeamA = TeamSelection.Something.PlayerModel.init(firstName: dict.object(forKey: "firstName") as! String, lastName: dict.object(forKey: "lastName") as! String, email: dict.object(forKey: "email") as! String, userRating: dict.object(forKey: "userRating") as! NSNumber, teamOption: dict.object(forKey: "teamOption") as! String, numOfValues: 0, id: dict.object(forKey: "id") as! String, userId: dict.object(forKey: "Userid") as! String, teamCaptain: dict.object(forKey: "teamCaptain") as! Bool, groupID: dict.object(forKey: "groupId") as! String, groupName: dict.object(forKey: "groupName") as! String)
            playerModel.groupArrayA.add(playerTeamA)
        }
        else{
            let playerTeamB = TeamSelection.Something.PlayerModel.init(firstName: dict.object(forKey: "firstName") as! String, lastName: dict.object(forKey: "lastName") as! String, email: dict.object(forKey: "email") as! String, userRating: dict.object(forKey: "userRating") as! NSNumber, teamOption: dict.object(forKey: "teamOption") as! String, numOfValues: 0, id: dict.object(forKey: "id") as! String, userId: dict.object(forKey: "Userid") as! String, teamCaptain: dict.object(forKey: "teamCaptain") as! Bool, groupID: dict.object(forKey: "groupId") as! String, groupName: dict.object(forKey: "groupName") as! String)
            playerModel.groupArrayB.add(playerTeamB)
        }
    }
    viewController?.displayPlayerInformation(playerModel: playerModel)
}
}
