//
//  TeamSelectionPresenter.swift
//  SampleCS
//
//  Created by Adam Johnston on 15/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TeamSelectionPresentationLogic
{
  func presentSomething(response: TeamSelection.Something.TeamResponse)
  func displayTeamData(showing: NSDictionary)

}

class TeamSelectionPresenter: TeamSelectionPresentationLogic
{
  weak var viewController: TeamSelectionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TeamSelection.Something.TeamResponse)
  {
    let viewModel = TeamSelection.Something.TeamResponse()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
  func displayTeamData(showing: NSDictionary){
    
    
  }
}
