//
//  TeamSelectionViewController.swift
//  SampleCS
//
//  Created by Adam Johnston on 15/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseFirestore
import IQKeyboardManagerSwift

protocol TeamSelectionDisplayLogic: class
{
  func displaySomething(viewModel: TeamSelection.Something.TeamResponse)
}

class TeamSelectionViewController: UIViewController, TeamSelectionDisplayLogic
{
  var interactor: TeamSelectionBusinessLogic?
  var router: (NSObjectProtocol & TeamSelectionRoutingLogic & TeamSelectionDataPassing)?

  @IBOutlet weak var addPlayerCollection: UICollectionView!
  @IBOutlet weak var unassignedButton: UIBarButtonItem!
  @IBOutlet weak var addUserView: AddUserView!

  var groupID : NSString = ""

  // MARK: Object lifecycle
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = TeamSelectionInteractor()
    let presenter = TeamSelectionPresenter()
    let router = TeamSelectionRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    getTeamData()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func getTeamData()
  {
    var request = TeamSelection.Something.TeamRequest()
    request.groupID = (router?.groupID)!
    interactor?.doSomething(request: request, currentInteractor: interactor as! TeamSelectionInteractor)
  }
  
  func displaySomething(viewModel: TeamSelection.Something.TeamResponse)
  {
    //nameTextField.text = viewModel.name
  }
}
