//
//  LoginRouter.swift
//  SampleCS
//
//  Created by Adam Johnston on 08/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToSomewhere()
    func routeToAddPlayerInfo()
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    func routeToSomewhere(){
        viewController?.performSegue(withIdentifier: "addPlayerInformation", sender: nil)
    }
    
    func routeToAddPlayerInfo() {
        viewController?.performSegue(withIdentifier: "addPlayerInformation", sender: nil)
    }
    
    
    //MARK: Navigation
    
    func navigateToSomewhere(source: LoginViewController, destination: AddPlayerDetailsViewController){
        source.show(destination, sender: nil)
    }
    
    //MARK: Passing data
    
    func passDataToSomewhere(source: LoginDataStore, destination: inout AddPlayerDetailsDataStore){
        //    destination.name = source.name
        
        source
    }
}
