//
//  LoginModels.swift
//  SampleCS
//
//  Created by Adam Johnston on 08/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FBSDKCoreKit
import FBSDKLoginKit
import Firebase

enum Login
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            var tokenString = FBSDKAccessToken.current().tokenString
            var token = FacebookAuthProvider.credential(withAccessToken: FBSDKAccessToken.current().tokenString)
        }
        struct AddUserToggleScreen
        {
            var showUserScreen : Bool
        }
        struct noTokenRequest
        {
            var tokenString = ""
            var token : AuthCredential? = nil
        }
        struct Response
        {
            var alreadyLoggedIn : Bool
        }
        struct PlayerModel
        {
            var firstName = String()
            var lastName = String()
            var email = String()
            var userRating = NSNumber()
            var teamOption = String()
            var numOfValues = Int()
            var id = String()
            var userId = String()
            var teamCaptain = Bool()
            var groupID = String()
            var groupName = String()
        }
        struct RegisterModel
        {
            var email = String()
            var password = String()
        }
    }
}
