//
//  MarkTestInteractor.swift
//  SampleCS
//
//  Created by Adam Johnston on 13/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com

import UIKit

protocol MarkTestBusinessLogic
{
  func doSomething(request: MarkTest.Something.Request)
}

protocol MarkTestDataStore
{
  //var name: String { get set }
}

class MarkTestInteractor: MarkTestBusinessLogic, MarkTestDataStore
{
  var presenter: MarkTestPresentationLogic?
  var worker: MarkTestWorker?
  //var name: String = ""
  // MARK: Do something
  
  func doSomething(request: MarkTest.Something.Request)
  {
    let callStringWtihClosure = {(response: MarkTest.Something.Response) -> () in
        self.presenter?.presentSomething(response: response)
    }
    worker = MarkTestWorker()
    worker?.doSomeWork(parameter: callStringWtihClosure);
  }
}
