//
//  MarkTestPresenter.swift
//  SampleCS
//
//  Created by Adam Johnston on 13/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarkTestPresentationLogic
{
  func presentSomething(response: MarkTest.Something.Response)
}

class MarkTestPresenter: MarkTestPresentationLogic
{
  weak var viewController: MarkTestDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MarkTest.Something.Response)
  {
    let viewModel = MarkTest.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
