//
//  EditPlayerDetailsPresenter.swift
//  SampleCS
//
//  Created by Adam Johnston on 20/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditPlayerDetailsPresentationLogic
{
  func presentSomething(response: EditPlayerDetails.Something.Response)
}

class EditPlayerDetailsPresenter: EditPlayerDetailsPresentationLogic
{
  weak var viewController: EditPlayerDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EditPlayerDetails.Something.Response)
  {
    let viewModel = EditPlayerDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
