//
//  EditPlayerDetailsRouter.swift
//  SampleCS
//
//  Created by Adam Johnston on 20/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditPlayerDetailsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    var player : EditPlayerDetails.Something.PlayerModel {get set}
    func routeToPlayerInfo()
}

protocol EditPlayerDetailsDataPassing
{
  var dataStore: EditPlayerDetailsDataStore? { get }
}

class EditPlayerDetailsRouter: NSObject, EditPlayerDetailsRoutingLogic, EditPlayerDetailsDataPassing
{
 var player: EditPlayerDetails.Something.PlayerModel = EditPlayerDetails.Something.PlayerModel()
    
  weak var viewController: EditPlayerDetailsViewController?
  var dataStore: EditPlayerDetailsDataStore?
  
    
    func routeToPlayerInfo() {
        viewController?.performSegue(withIdentifier: "playerInformation", sender: nil)
    }

  // MARK: Routing
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  //func navigateToSomewhere(source: EditPlayerDetailsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  //func passDataToSomewhere(source: EditPlayerDetailsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
