//
//  EditPlayerDetailsPresenter.swift
//  SampleCS
//
//  Created by Adam Johnston on 20/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditPlayerDetailsPresentationLogic
{
  func presentSomething(player: EditPlayerDetails.Something.PlayerModel)
  func successfulPlayerCount(response: EditPlayerDetails.Something.ResponseGroups)
}

class EditPlayerDetailsPresenter: EditPlayerDetailsPresentationLogic
{
  weak var viewController: EditPlayerDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(player: EditPlayerDetails.Something.PlayerModel)
  {
    viewController?.displaySomething(player: player)
  }
    
    func successfulPlayerCount(response: EditPlayerDetails.Something.ResponseGroups) {
        viewController?.successfulTeamCount(response: response)
    }
}
