//
//  EditPlayerDetailsInteractor.swift
//  SampleCS
//
//  Created by Adam Johnston on 20/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditPlayerDetailsBusinessLogic
{
  func doSomething(request: EditPlayerDetails.Something.PlayerModel, currentInteractor: EditPlayerDetailsInteractor)
  func playerUpdatedSuccess(player: EditPlayerDetails.Something.PlayerModel, currentInteractor: EditPlayerDetailsInteractor)
  func countUsersInTeam(request: EditPlayerDetails.Something.PlayerModel, currentInteractor: EditPlayerDetailsInteractor)
  func successfulCount(response: EditPlayerDetails.Something.ResponseGroups, currentInteractor: EditPlayerDetailsInteractor)
}

protocol EditPlayerDetailsDataStore
{
  //var name: String { get set }
}

class EditPlayerDetailsInteractor: EditPlayerDetailsBusinessLogic, EditPlayerDetailsDataStore
{
  var presenter: EditPlayerDetailsPresentationLogic?
  var worker: EditPlayerDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EditPlayerDetails.Something.PlayerModel, currentInteractor: EditPlayerDetailsInteractor)
  {
    worker = EditPlayerDetailsWorker()
    worker?.doSomeWork(player: request, currentInteractor: currentInteractor)
  }
    
    func playerUpdatedSuccess(player: EditPlayerDetails.Something.PlayerModel, currentInteractor: EditPlayerDetailsInteractor) {
        presenter?.presentSomething(player : player)
    }
    
    func countUsersInTeam(request: EditPlayerDetails.Something.PlayerModel, currentInteractor: EditPlayerDetailsInteractor) {
        worker = EditPlayerDetailsWorker()
        worker?.countCurrentPlayers(details: request, currentInteractor: currentInteractor)
    }
    
    func successfulCount(response: EditPlayerDetails.Something.ResponseGroups, currentInteractor: EditPlayerDetailsInteractor) {
        presenter?.successfulPlayerCount(response: response)
    }


}
