//
//  EditPlayerDetailsInteractor.swift
//  SampleCS
//
//  Created by Adam Johnston on 20/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditPlayerDetailsBusinessLogic
{
  func doSomething(request: EditPlayerDetails.Something.Request)
}

protocol EditPlayerDetailsDataStore
{
  //var name: String { get set }
}

class EditPlayerDetailsInteractor: EditPlayerDetailsBusinessLogic, EditPlayerDetailsDataStore
{
  var presenter: EditPlayerDetailsPresentationLogic?
  var worker: EditPlayerDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EditPlayerDetails.Something.Request)
  {
    worker = EditPlayerDetailsWorker()
    worker?.doSomeWork()
    
    let response = EditPlayerDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
