//
//  JoinSquadPresenter.swift
//  SampleCS
//
//  Created by Adam Johnston on 14/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol JoinSquadPresentationLogic
{
    func presentGroups(response: JoinSquad.Something.ResponseGroups)
    func successfulPlayerAdd()
}

class JoinSquadPresenter: JoinSquadPresentationLogic
{
    weak var viewController: JoinSquadDisplayLogic?
    
    // MARK: Do something
    func presentGroups(response: JoinSquad.Something.ResponseGroups)
    {
        let details = JoinSquad.Something.GroupModel(groupArray: [])
        let group = response.groupArray
        for i in 0...group.count-1{
            let dict : NSDictionary = group.object(at: i) as! NSDictionary
            details.groupArray.add(["groupName" : dict.object(forKey: "groupName") as! String, "groupID" : dict.object(forKey: "groupID") as! String])
        }
        viewController?.displaySomething(response: details, teamCountA: 0, teamCountB: 0)
    }
    
    func successfulPlayerAdd() {
        viewController?.successfulTeamJoin()
    }
}
