//
//  JoinSquadModels.swift
//  SampleCS
//
//  Created by Adam Johnston on 14/11/2018.
//  Copyright (c) 2018 Adam Johnston. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum JoinSquad
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            var userId = String()
        }
        struct ResponseGroups
        {
            var groupArray = NSMutableArray()
            var teamACount = Int()
            var teamBCount = Int()
            var teamUnassignedCount = Int()
        }
        
        struct RequestToAdd
        {
            var userId = String()
            var selectedGroup = NSDictionary()
        }
        struct ResponseToAdding
        {
            //        var userId = String()
            //        var selectedGroup = NSDictionary()
        }
        
        struct GroupModel
        {
            var groupArray : NSMutableArray
        }
        
        class PlayerModel : NSObject
        {
            var firstName = String()
            var lastName = String()
            var email = String()
            var userRating = NSNumber()
            var teamOption = String()
            var numOfValues = Int()
            var id = String()
            var userId = String()
            var teamCaptain = Bool()
            var groupID = String()
            var groupName = String()
        }

    }
}
